Upgrade laminas-coding-standard to 2.3
laminas/laminas-config-aggregator pull request #19
Opened 2021-10-11 11:53 UTC by arueckauer

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

This PR updates the `laminas-coding-standard` to version `2.3.0` and provides necessary code changes.

2021-10-21 14:39 UTC, Ocramius requested changes

2021-10-21 14:39 UTC, Ocramius commented on src/ConfigAggregator.php
> +                static::class,
Does `$var::class` work on PHP 7.3? Seems wrong

2021-10-21 16:04 UTC, arueckauer commented on src/ConfigAggregator.php
> +                static::class,
This is possible [since 7.0](https://3v4l.org/ePSji#v7.0.0). Could not find the section in the official documentation.

2021-10-26 10:59 UTC, Ocramius approved these changes
LGTM :ship: 

Thanks @arueckauer!

2021-10-26 10:59 UTC, merged