Add support for `brick/varexporter` 0.5.0
laminas/laminas-config-aggregator pull request #45
Opened 2024-05-10 20:08 UTC by acelaya

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This PR adds support for `brick/varexporter` v0.5.0, which in turn supports `nikic/PHP-Parser` 5, enabling upgrades to PHPUnit 11 in downstream projects.

2024-05-12 09:36 UTC, Ocramius requested changes

2024-05-12 09:36 UTC, Ocramius commented on composer.json
> +        "brick/varexporter": "^0.5.0 || ^0.4.0",
`composer.lock` requires hashing again

2024-05-12 09:53 UTC, acelaya commented on composer.json
> +        "brick/varexporter": "^0.5.0 || ^0.4.0",
Oops, my mistake. Should be done now.

2024-05-12 10:00 UTC, Ocramius approved these changes
Thanks!

2024-05-12 10:00 UTC, merged

2024-05-14 09:17 UTC, snapshotpl commented
@acelaya @Ocramius here is same problem like with https://github.com/laminas/laminas-servicemanager/pull/237

`  - Downloading brick/varexporter (0.4.0)`